version: '2'

services:
  db:
    image: mariadb:10.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware

  shopware:
    build: .
    environment: 
      DB_HOST: db
      DB_USER: shopware
      DB_PASSWORD: shopware
      DB_NAME: shopware
      SHOP_HOST: "localhost:8000"
    volumes_from:
      - data
    ports:
      - "8000:80"
    depends_on:
      - db

  data:
    image: tianon/true
    volumes:
      - .:/project
      - ./sw:/var/www/html